---
- name: Deploy terraform project
  hosts: localhost
  tasks:
  - name: Initialize terraform project
    shell: terraform init ./project

  - name: Build terraform deployment
    shell: terraform plan ./project

  - name: Deployment
    terraform:
      project_path: './project/'
      state: present
